# FxQ build identification generator
#
# Runs as a pre-build step (see extra_scripts in each project's
# platformio.ini) so build number/date/time/git commit never need
# updating by hand. Shared by every FxQ project - project-specific state
# (the build counter, the generated header) lives under that project's
# own directory, keyed off PROJECT_DIR, so TX and RX each get their own
# independent build numbering.
#
# Writes src/FxQBuildInfo.h - do not edit that file directly, it's
# regenerated on every build.

import datetime
import os
import subprocess

Import("env")

project_dir = env["PROJECT_DIR"]
counter_path = os.path.join(project_dir, "build_number.txt")

build_number = 1
if os.path.exists(counter_path):
    try:
        with open(counter_path) as f:
            build_number = int(f.read().strip()) + 1
    except ValueError:
        build_number = 1

with open(counter_path, "w") as f:
    f.write(str(build_number))

try:
    git_commit = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"],
        cwd=project_dir,
        stderr=subprocess.DEVNULL,
    ).decode().strip()
except Exception:
    git_commit = "unknown"

now = datetime.datetime.now()

header_lines = [
    "#pragma once",
    "",
    "// Auto-generated by generate_build_info.py at build time.",
    "// Do not edit - changes here are overwritten on the next build.",
    "",
    "#define FXQ_BUILD_NUMBER {}".format(build_number),
    "#define FXQ_BUILD_DATE \"{}\"".format(now.strftime("%Y-%m-%d")),
    "#define FXQ_BUILD_TIME \"{}\"".format(now.strftime("%H:%M")),
    "#define FXQ_GIT_COMMIT \"{}\"".format(git_commit),
    "",
]

header_path = os.path.join(project_dir, "src", "FxQBuildInfo.h")
with open(header_path, "w") as f:
    f.write("\n".join(header_lines))
